name: Cypress Tests

on: [push]

jobs:
build:
runs-on: ubuntu-16.04
timeout-minutes: 10
steps:
- uses: actions/checkout@v2
- name: nodejs server
uses: actions/setup-node@v1
with:
node-version: "12.x"
- run: |
npm ci
npm run build
npm run start &
- name: Cypress run
uses: cypress-io/github-action@v1
with:
browser: electron
wait-on: http://localhost:3000
# record: true
# group: "Default tests"
# env:
# CYPRESS_RECORD_KEY: ${{ secrets.CYPRESS_RECORD_KEY }}
- uses: actions/upload-artifact@v1
if: failure()
with:
name: cypress-videos
path: cypress/videos

