name: rubiks-cube-action
on: [push]
jobs:
  cypress-run:
    runs-on: windows-latest
    steps:
        - uses: actions/checkout@v2
        - uses: cypress-io/github-action@v2
          with:
            browser: electron
            wait-on: https://localhost:3000

