name: rubiks-cube-action
on: [push]
jobs:
  cypress-run:
    runs-on: windows-latest
    steps:
        - uses: actions/checkout@v2
        - run: npm start
        - uses: cypress-io/github-action@v2

