name: rubiks-cube-action
on: [push]
jobs:
  cypress-run:
    name: Cypress run
    runs-on: windowns-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v2
      - name: Cypress run
        uses: cypress-io/github-action@v2
        with:
          start: npm start
          start-windows: npm run start:windows::server
